### ISSUE TITLE
The modification of the OCI Spec should add device Cgroup rules

### ISSUE THREAD

**Issue by elezar** [container-orchestrated-devices/container-device-interface#46]
In order to get the CDI spec for NVIDIA devices to function as expected with podman, I needed to add the relevant `--device-cgroup-rule` flags for the devices injected into the container as shown below.
```
$ sudo ./podman run -ti --net=host --device-cgroup-rule="c 195:255 rmw" --device-cgroup
-rule="c 195:0 rwm" --device=nvidia.com/experimental=GPU-edfee158-11c1-52b8-0517-92f30e7fac88 ubuntu:18.04
WARN[0000] Ignoring global metacopy option, not supported with booted kernel
root@dgx0126:/# ldconfig
root@dgx0126:/# nvidia-smi -L
GPU 0: Tesla V100-SXM2-16GB-N (UUID: GPU-edfee158-11c1-52b8-0517-92f30e7fac88)
```

Not doing so causes the `nvidia-smi` command to fail with (for example):
```
stat("/dev/nvidiactl", {st_mode=S_IFCHR|0666, st_rdev=makedev(195, 255), ...}) = 0
openat(AT_FDCWD, "/dev/nvidiactl", O_RDWR) = -1 EPERM (Operation not permitted)
openat(AT_FDCWD, "/dev/nvidiactl", O_RDONLY) = -1 EPERM (Operation not permitted)
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
write(1, "Failed to initialize NVML: Unkno"..., 41Failed to initialize NVML: Unknown Error
```
Or not detect a device if the `195:0` rule is not added.

The injection code for CDI should be updated to also add the required CGroup device rules to the OCI Spec. For example, I have used the following in the past:
```
	// TODO: These need to be configurable
	deviceFileMode := os.FileMode(8630)
	deviceUID := uint32(0)
	deviceGID := uint32(0)

	deviceMajor := int64(d.Major)
	deviceMinor := int64(d.Minor)

	d.logger.Infof("Adding device %v", d.Path)
	ociDevice := specs.LinuxDevice{
		Path:     string(d.Path),
		Type:     "c",
		Major:    deviceMajor,
		Minor:    deviceMinor,
		FileMode: &deviceFileMode,
		UID:      &deviceUID,
		GID:      &deviceGID,
	}
	spec.Linux.Devices = append(spec.Linux.Devices, ociDevice)

	ociDeviceCgroup := specs.LinuxDeviceCgroup{
		Allow:  true,
		Type:   "c",
		Major:  &deviceMajor,
		Minor:  &deviceMinor,
		Access: "rwm",
	}

	// TODO: We have to handle the case where we are updating the cgroups for multiple devices
	// leading to duplicates in the spec
	spec.Linux.Resources.Devices = append(spec.Linux.Resources.Devices, ociDeviceCgroup)
```

One question is whether this should be opt-in or separate from the device nodes themselves? That is to say that we extend the container edits of the CDI spec to support cgroup modification.

**Comment by klihub** [comment]
Hmm... I think we do it, or at least try to inject the right cgroup access control rules. Here...
https://github.com/container-orchestrated-devices/container-device-interface/blob/ee12044b3895afdff3841fee894e3edf01d7fc26/pkg/cdi/container-edits.go#L112

You can easily test your CDI Specs and how the `OCI Spec` modifications look like using the `cdi` test utility like this:
```
root@e2e-fedora-crio:/home/fedora[root@e2e-fedora-crio fedora]# ls -ls /etc/cdi
total 4
4 -rw-r--r-- 1 root root 1106 Feb  3 14:49 loop-devs.yaml
root@e2e-fedora-crio:/home/fedora[root@e2e-fedora-crio fedora]# ./cdi devices
CDI devices found:
  0. vendor1.com/loop=dev0
  1. vendor1.com/loop=dev1
root@e2e-fedora-crio:/home/fedora[root@e2e-fedora-crio fedora]# echo "" | ./cdi inject - vendor1.com/loop=dev0
Updated OCI Spec:
  hooks:
    startContainer:
    - args:
      - /bin/touch
      - /tmp/vendor1.present
      path: /bin/touch
    - args:
      - /bin/touch
      - /tmp/loop0.injected
      path: /bin/touch
  linux:
    devices:
    - fileMode: 432
      major: 7
      minor: 0
      path: /dev/loop0
      type: b
    resources:
      devices:
      - access: rwm
        allow: true
        major: 7
        minor: 0
        type: b
  mounts:
  - destination: /mnt/host/etc/hosts
    options:
    - ro
    - bind
    source: /etc/hosts
    type: bind
  ociVersion: ""
  process:
    cwd: ""
    env:
    - VENDOR1=present
    - LOOP0=injected
    user:
      gid: 0
      uid: 0
root@e2e-fedora-crio:/home/fedora[root@e2e-fedora-crio fedora]# 
```
